---
- name: Deploy updated Docker container from ECR
  hosts: api-server
  become: yes

  vars:
    container_name: api
    image_repository: 046504469503.dkr.ecr.us-east-1.amazonaws.com/cicd-test
    image_tag: latest

  tasks:
    - name: Login to ECR
      shell:  >
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 046504469503.dkr.ecr.us-east-1.amazonaws.com

    - name: Pull image from ECR
      docker_image:
        name: "{{ image_repository }}:{{ image_tag }}"
        source: pull

    - name: Run the new container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_repository }}:{{ image_tag }}"
        state: started
        ports:
          - "80:5000"
        restart_policy: always