---
- name: Deploy updated Docker container from ECR
  hosts: api-server
  become: yes

  vars:
    container_name: api
    image_repository: 046504469503.dkr.ecr.us-east-1.amazonaws.com/cicd-test
    image_tag: latest

  tasks:
    - name: Run the new container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_repository }}:{{ image_image_tag }}"
        state: started
        ports:
          - "80:5000"