---
- name: Delete existing container and image
  hosts: api-server
  become: yes

  vars:
    container_name: api
    image_repository: 046504469503.dkr.ecr.us-east-1.amazonaws.com/cicd-test
    image_tag: latest

  tasks:
    - name: Stop the running container
      docker_container:
        name: "{{ container_name }}"
        state: stopped
      ignore_errors: yes

    - name: Delete the container
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Remove the Docker image
      docker_image:
        name: "{{ image_repository }}:{{ image_tag }}"
        state: absent
      ignore_errors: yes